# Generated by Django 4.1.3 on 2022-12-12 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("asset_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="bic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="iban",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts",
                to="asset_management.accounttype",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asset_management",
                to="asset_management.account",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="asset",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="asset_management", to="asset_management.assettag"
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asset_management",
                to="asset_management.assettype",
            ),
        ),
        migrations.AlterField(
            model_name="assetvalue",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_values",
                to="asset_management.asset",
            ),
        ),
        migrations.AlterField(
            model_name="assetvalue",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="institution",
            name="background",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="institution",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="institution",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="institution",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="institutions",
                to="asset_management.institutiontype",
            ),
        ),
        migrations.AlterField(
            model_name="userinstitution",
            name="identifier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userinstitution",
            name="password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
