# Generated by Django 4.1.3 on 2022-12-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset_management", "0003_remove_assetvalue_quantity_assetquantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="tags",
            field=models.ManyToManyField(related_name="asset_management", to="asset_management.assettag"),
        ),
    ]
