# Generated by Django 4.1.3 on 2023-01-07 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0001_initial"),
        ("asset_management", "0004_alter_asset_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exchangerate",
            name="from_currency",
        ),
        migrations.RemoveField(
            model_name="exchangerate",
            name="to_currency",
        ),
        migrations.AlterField(
            model_name="assetvalue",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="market_data.currency"
            ),
        ),
        migrations.AlterField(
            model_name="balance",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="market_data.currency"
            ),
        ),
        migrations.DeleteModel(
            name="Currency",
        ),
        migrations.DeleteModel(
            name="ExchangeRate",
        ),
    ]
