# Generated by Django 4.1.3 on 2023-01-07 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0001_initial"),
        ("asset_management", "0005_remove_exchangerate_from_currency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="accounting_value",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="account",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="market_data.currency",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="account",
            name="instant_value",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Balance",
        ),
        migrations.AddField(
            model_name="accountvalue",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balances",
                to="asset_management.account",
            ),
        ),
    ]
