# Generated by Django 4.1.3 on 2023-01-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset_management", "0006_accountvalue_account_accounting_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="reference",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
