# Generated by Django 4.1.3 on 2023-01-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset_management", "0008_rename_unit_amount_assetvalue_unit_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
