# Generated by Django 4.1.3 on 2023-01-14 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asset_management", "0009_alter_account_reference"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="instant_value",
            new_name="value",
        ),
        migrations.RemoveField(
            model_name="account",
            name="accounting_value",
        ),
    ]
