# Generated by Django 4.1.3 on 2023-01-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset_management", "0010_rename_instant_value_account_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="unrealized_gain_value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
