# Generated by Django 4.1.3 on 2023-01-21 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0007_currency_country"),
        ("asset_management", "0011_account_unrealized_gain_value"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="unrealized_gain_value",
            new_name="unrealized_pnl_value",
        ),
        migrations.RenameField(
            model_name="assetvalue",
            old_name="unit_value",
            new_name="value",
        ),
        migrations.RemoveField(
            model_name="assetvalue",
            name="currency",
        ),
        migrations.AddField(
            model_name="asset",
            name="break_even_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="market_data.currency",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="asset",
            name="value",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
