# Generated by Django 4.1.3 on 2023-01-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset_management", "0014_remove_asset_user_alter_asset_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="quantity",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
