# Generated by Django 4.1.3 on 2023-01-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AssetType",
            new_name="MarketAssetType",
        ),
    ]
