# Generated by Django 4.1.3 on 2023-01-12 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0004_rename_asset_marketassetvalue_market_asset"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marketassetvalue",
            old_name="unit_amount",
            new_name="close",
        ),
        migrations.AddField(
            model_name="marketasset",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="market_data.currency",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="marketasset",
            name="value",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="marketassetvalue",
            name="high",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketassetvalue",
            name="low",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketassetvalue",
            name="open",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketassetvalue",
            name="volume",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
