# Generated by Django 4.1.3 on 2023-01-14 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0005_rename_unit_amount_marketassetvalue_close_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marketassetvalue",
            name="currency",
        ),
    ]
