# Generated by Django 4.1.3 on 2023-01-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0006_remove_marketassetvalue_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
