# Generated by Django 4.1.3 on 2023-01-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0007_currency_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketasset",
            name="link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
